-- Maintenance script for ETD degree names
-- Last update: 2018-03-14

USE etd;

DROP TABLE degree_name_ref;

CREATE TABLE IF NOT EXISTS degree_name_ref (
	  degree_name_id INT(10) UNSIGNED NOT NULL,
	  degree_name_short VARCHAR(10) NOT NULL,
	  degree_name_long VARCHAR(100) NOT NULL,
	  PRIMARY KEY (degree_name_id));

INSERT INTO degree_name_ref (degree_name_id, degree_name_short, degree_name_long) VALUES
(1,'NULL','Candidate in Philosophy'),
(2,'DA','Doctor of Arts (DA)'),
(3,'AuD','Doctor of Audiology (AuD)'),
(4,'DBA','Doctor of Business Administration (DBA)'),
(5,'DMD','Doctor of Dental Medicine (DMD)'),
(6,'Ded','Doctor of Education (Ded)'),
(7,'EdD','Doctor of Education (EdD)'),
(8,'DEng','Doctor of Engineering (DEng)'),
(9,'HSD','Doctor of Health and Safety (HSD)'),
(10,'DMgt','Doctor of Management (DMgt)'),
(11,'DMin','Doctor of Ministry (DMin)'),
(12,'DM','Doctor of Music (DM)'),
(13,'DME','Doctor of Music Education (DME)'),
(14,'DMA','Doctor of Musical Arts (DMA)'),
(15,'ND','Doctor of Nursing (ND)'),
(16,'DNS','Doctor of Nursing Science (DNS)'),
(17,'PharmD','Doctor of Pharmacy (PharmD)'),
(18,'NULL','Doctor of Philosophy (Medical Science)'),
(19,'PhD','Doctor of Philosophy (PhD)'),
(20,'HSOP','Doctor of Philosophy in Health Services Research (HSOP)'),
(21,'PED','Doctor of Physical Education (PED)'),
(22,'DPT','Doctor of Physical Therapy (DPT)'),
(23,'DPDS','Doctor of Planning and Development Studies (DPDS)'),
(24,'PsyD','Doctor of Psychology (PsyD)'),
(25,'DPA','Doctor of Public Administration (DPA)'),
(26,'DrPH','Doctor of Public Health (DrPH)'),
(27,'ReD','Doctor of Recreation (ReD)'),
(28,'RhD','Doctor of Rehabilitation (RhD)'),
(29,'DSW','Doctor of Social Work (DSW)'),
(30,'DVM','Doctor of Veterinary Medicine (DVM)'),
(31,'EdS','Education Specialist (EdS)'),
(32,'IMES','International Master of Environmental Sciences (IMES)'),
(33,'JD','Juris Doctorate (JD)'),
(34,'MAS','Master in Advanced Studies (MAS)'),
(35,'MAM','Master in Agricultural Management (MAM)'),
(36,'MMT','Master in Management of Technology (MMT)'),
(37,'MT','Master in Taxation (MT)'),
(38,'MAcc','Master of Accounting (MAcc)'),
(39,'MAeroE','Master of Aeronautical Engineering (MAeroE)'),
(40,'MAgEd','Master of Agricultural Education (MAgEd)'),
(41,'MAgr','Master of Agriculture (MAgr)'),
(42,'MAE','Master of Architectural Engineering (MAE)'),
(43,'MArch','Master of Architecture (MArch)'),
(44,'MArch','Master of Architecture (MArch)/Master of Business Administration (MBA)'),
(45,'MArch','Master of Architecture (MArch)/Master of Fine Arts (MFA)'),
(46,'MArch','Master of Architecture (MArch)/Master of Urban Planning (MUP)'),
(47,'MA','Master of Arts (MA)'),
(48,'MAC','Master of Arts in Counseling (MAC)'),
(49,'MAE','Master of Arts in Education (MAE)'),
(50,'MAIS','Master of Arts in Interdisciplinary Studies (MAIS)'),
(51,'MAPC','Master of Arts in Pastoral Counseling (MAPC)'),
(52,'MAR','Master of Arts in Religion (MAR)'),
(53,'MAT','Master of Arts in Teaching (MAT)'),
(54,'MATE','Master of Arts in the Teaching of English (MATE)'),
(55,'MBioSci','Master of Biological Science (MBioSci)'),
(56,'MBS','Master of Building Science (MBS)'),
(57,'MBA','Master of Business Administration (MBA)'),
(58,'NULL','Master of Business Administration/Master of Science in Information Systems'),
(59,'MBT','Master of Business Taxation (MBT)'),
(60,'MCTE','Master of Career and Technology Education (MCTE)'),
(61,'MChE','Master of Chemical Engineering (MChE)'),
(62,'MCRP','Master of City and Regional Planning (MCRP)'),
(63,'MCE','Master of Civil Engineering (MCE)'),
(64,'NULL','Master of Community Planning'),
(65,'MCIS','Master of Computer and Information Science (MCIS)'),
(66,'MCompE','Master of Computer Engineering (MCompE)'),
(67,'MCM','Master of Construction Management (MCM)'),
(68,'MCSM','Master of Construction Science and Management (MCSM)'),
(69,'MCJ','Master of Criminal Justice (MCJ)'),
(70,'MDiv','Master of Divinity (MDiv)'),
(71,'MEd','Master of Education (MEd)'),
(72,'MEE','Master of Electrical Engineering (MEE)'),
(73,'MECom','Master of Electronic Commerce (MECom)'),
(74,'ME','Master of Engineering (ME)'),
(75,'MEngr','Master of Engineering (MEngr)'),
(76,'MEnvE','Master of Environmental Engineering (MEnvE)'),
(77,'MES','Master of Environmental Studies (MES)'),
(78,'MFA','Master of Fine Arts (MFA)'),
(79,'MFR','Master of Forest Resources (MFR)'),
(80,'MF','Master of Forestry (MF) '),
(81,'MGS','Master of General Studies (MGS)'),
(82,'MGIS','Master of Geographic Information Science (MGIS)'),
(83,'MGeoE','Master of Geomechanics Engineering (MGeoE)'),
(84,'MHA','Master of Health Administration (MHA)'),
(85,'MHP','Master of Historic Preservation (MHP)'),
(86,'MHAMS','Master of Historical Administration and Museum Studies (MHAMS)'),
(87,'MHD','Master of Human Development (MHD)'),
(88,'MHRD','Master of Human Resource Development (MHRD)'),
(89,'MIDS','Master of Interdisciplinary Studies (MIDS)'),
(90,'MIM','Master of International Management (MIM)'),
(91,'MJS','Master of Judicial Studies (MJS)'),
(92,'MLA','Master of Landscape Architecture (MLA)'),
(93,'MLS','Master of Library Science/Master of Life Sciences (MLS)'),
(94,'MM','Master of Management (MM)'),
(95,'MMatSE','Master of Materials Science and Engineering (MMatSE)'),
(96,'MM','Master of Music (MM)'),
(97,'MMUS','Master of Music (MMUS)'),
(98,'MME','Master of Music Education (MME)'),
(99,'MPRTM','Master of Parks, Recreation and Tourism Management (MPRTM)'),
(100,'MPT','Master of Physical Therapy (MPT)'),
(101,'MPlan','Master of Planning (MPlan)'),
(102,'MPAcc','Master of Professional Accounting (MPAcc)'),
(103,'MPA','Master of Public Administration (MPA)'),
(104,'MPA/JD','Master of Public Administration/Juris Doctorate (MPA/JD)'),
(105,'MPH','Master of Public Health (MPH)'),
(106,'MPM','Master of Public Management (MPM)'),
(107,'MPP','Master of Public Policy (MPP)'),
(108,'MRED','Master of Real Estate Development (MRED)'),
(109,'MRP','Master of Regional Planning (MRP)'),
(110,'MSA','Master of School Administration (MSA)'),
(111,'MS','Master of Science (MS)'),
(112,'MSSE','Master of Science and Software Engineering (MSSE)'),
(113,'MSA','Master of Science in Acountancy (MSA)'),
(114,'MSA','Master of Science in Administration (MSA)'),
(115,'MSAeroE','Master of Science in Aerospace Engineering (MSAeroE)'),
(116,'MSAgE','Master of Science in Agricultural Engineering (MSAgE)'),
(117,'NULL','Master of Science in Biomedical Engineering'),
(118,'MSBiosyAgE','Master of Science in Biosystems and Agricultural Engineering (MSBiosyAgE)'),
(119,'MSChE','Master of Science in Chemical Engineering (MSChE)'),
(120,'MSCE','Master of Science in Civil Engineering (MSCE)'),
(121,'MSCRP','Master of Science in Community and Regional Planning (MSCRP)'),
(122,'MSECO','Master of Science in Economics (MSECO)'),
(123,'MSEd','Master of Science in Education (MSEd)'),
(124,'MSECE','Master of Science in Electrical and Computer Engineering (MSECE)'),
(125,'MSEE','Master of Science in Electrical Engineering (MSEE)'),
(126,'MSE','Master of Science in Engineering (MSE)'),
(127,'MSEM','Master of Science in Engineering Management (MSEM)'),
(128,'MSETM','Master of Science in Environmental Technology Management (MSETM)'),
(129,'MSHTM','Master of Science in Hospitality and Tourism Management (MSHTM)'),
(130,'MSHRM','Master of Science in Human Resources Management (MSHRM)'),
(131,'MSIE','Master of Science in Industrial Engineering (MSIE)'),
(132,'MSIEOR','Master of Science in Industrial Engineering and Operations Research (MSIEOR)'),
(133,'MSIS','Master of Science in Information Systems (MSIS)'),
(134,'MSISE','Master of Science in Infrastructure Systems Engineering (MSISE)'),
(135,'MSIS','Master of Science in Interdisciplinary Studies (MSIS)'),
(136,'MSIB','Master of Science in International Business (MSIB)'),
(137,'MSJ','Master of Science in Jurisprudence (MSJ)'),
(138,'MSM','Master of Science in Management (MSM)'),
(139,'MSMANFE','Master of Science in Manufacturing Engineering (MSMANFE)'),
(140,'MSMatSE','Master of Science in Material Science Engineering (MSMatSE)'),
(141,'MSMSE','Master of Science in Materials Science and Engineering (MSMSE)'),
(142,'MSME','Master of Science in Mechanical Engineering (MSME)'),
(143,'MSMS','Master of Science in Medical Sciences (MSMS)'),
(144,'MSN','Master of Science in Nursing (MSN)'),
(145,'MSPE','Master of Science in Petroleum Engineering (MSPE)'),
(146,'MSP','Master of Science in Planning (MSP)'),
(147,'MSPH','Master of Science in Public Health (MSPH)'),
(148,'MSW','Master of Social Welfare (MSW)'),
(149,'MSW','Master of Social Work (MSW)'),
(150,'MTS','Master of Theological Studies (MTS)'),
(151,'ThM','Master of Theology (ThM)'),
(152,'MURP','Master of Urban and Regional Planning (MURP)'),
(153,'MUP','Master of Urban Planning (MUP)'),
(154,'MHI','Master of Health Informatics (MHI)'),
(155,'MSB','Master of Science in Bioscience (MSB)'),
(156,'MST','Master of Science in Teaching (MST)'),
(157,'MD','Medical Doctor (MD)'),
(158,'MSExpSurg','Medical Surgeon in Experimental Surgery (MSExpSurg)'),
(159,'MSOtol','MS Otolaryngology (MSOtol)'),
(160,'PhDOtol','PhD Otolaryngology (PhDOtol)'),
(161,'PhDSurg','PhD Surgery (PhDSurg)'),
(162,'PMBA','Professional Master of Business Administration (PMBA)');
