INSERT INTO degree_name_ref VALUES (1,'NULL','Candidate in Philosophy');
INSERT INTO degree_name_ref VALUES (2,'DA','Doctor of Arts (DA)');
INSERT INTO degree_name_ref VALUES (3,'AuD','Doctor of Audiology (AuD)');
INSERT INTO degree_name_ref VALUES (4,'DBA','Doctor of Business Administration (DBA)');
INSERT INTO degree_name_ref VALUES (5,'DMD','Doctor of Dental Medicine (DMD)');
INSERT INTO degree_name_ref VALUES (6,'Ded','Doctor of Education (Ded)');
INSERT INTO degree_name_ref VALUES (7,'EdD','Doctor of Education (EdD)');
INSERT INTO degree_name_ref VALUES (8,'DEng','Doctor of Engineering (DEng)');
INSERT INTO degree_name_ref VALUES (9,'HSD','Doctor of Health and Safety (HSD)');
INSERT INTO degree_name_ref VALUES (10,'DMgt','Doctor of Management (DMgt)');
INSERT INTO degree_name_ref VALUES (11,'DMin','Doctor of Ministry (DMin)');
INSERT INTO degree_name_ref VALUES (12,'DM','Doctor of Music (DM)');
INSERT INTO degree_name_ref VALUES (13,'DME','Doctor of Music Education (DME)');
INSERT INTO degree_name_ref VALUES (14,'DMA','Doctor of Musical Arts (DMA)');
INSERT INTO degree_name_ref VALUES (15,'ND','Doctor of Nursing (ND)');
INSERT INTO degree_name_ref VALUES (16,'DNS','Doctor of Nursing Science (DNS)');
INSERT INTO degree_name_ref VALUES (17,'PharmD','Doctor of Pharmacy (PharmD)');
INSERT INTO degree_name_ref VALUES (18,'NULL','Doctor of Philosophy (Medical Science)');
INSERT INTO degree_name_ref VALUES (19,'PhD','Doctor of Philosophy (PhD)');
INSERT INTO degree_name_ref VALUES (20,'HSOP','Doctor of Philosophy in Health Services Research (HSOP)');
INSERT INTO degree_name_ref VALUES (21,'PED','Doctor of Physical Education (PED)');
INSERT INTO degree_name_ref VALUES (22,'DPT','Doctor of Physical Therapy (DPT)');
INSERT INTO degree_name_ref VALUES (23,'DPDS','Doctor of Planning and Development Studies (DPDS)');
INSERT INTO degree_name_ref VALUES (24,'PsyD','Doctor of Psychology (PsyD)');
INSERT INTO degree_name_ref VALUES (25,'DPA','Doctor of Public Administration (DPA)');
INSERT INTO degree_name_ref VALUES (26,'DrPH','Doctor of Public Health (DrPH)');
INSERT INTO degree_name_ref VALUES (27,'ReD','Doctor of Recreation (ReD)');
INSERT INTO degree_name_ref VALUES (28,'RhD','Doctor of Rehabilitation (RhD)');
INSERT INTO degree_name_ref VALUES (29,'DSW','Doctor of Social Work (DSW)');
INSERT INTO degree_name_ref VALUES (30,'DVM','Doctor of Veterinary Medicine (DVM)');
INSERT INTO degree_name_ref VALUES (31,'EdS','Education Specialist (EdS)');
INSERT INTO degree_name_ref VALUES (32,'IMES','International Master of Environmental Sciences (IMES)');
INSERT INTO degree_name_ref VALUES (33,'JD','Juris Doctorate (JD)');
INSERT INTO degree_name_ref VALUES (34,'MAS','Master in Advanced Studies (MAS)');
INSERT INTO degree_name_ref VALUES (35,'MAM','Master in Agricultural Management (MAM)');
INSERT INTO degree_name_ref VALUES (36,'MMT','Master in Management of Technology (MMT)');
INSERT INTO degree_name_ref VALUES (37,'MT','Master in Taxation (MT)');
INSERT INTO degree_name_ref VALUES (38,'MAcc','Master of Accounting (MAcc)');
INSERT INTO degree_name_ref VALUES (39,'MAeroE','Master of Aeronautical Engineering (MAeroE)');
INSERT INTO degree_name_ref VALUES (40,'MAgEd','Master of Agricultural Education (MAgEd)');
INSERT INTO degree_name_ref VALUES (41,'MAgr','Master of Agriculture (MAgr)');
INSERT INTO degree_name_ref VALUES (42,'MAE','Master of Architectural Engineering (MAE)');
INSERT INTO degree_name_ref VALUES (43,'MArch','Master of Architecture (MArch)');
INSERT INTO degree_name_ref VALUES (44,'MArch','Master of Architecture (MArch)/Master of Business Administration (MBA)');
INSERT INTO degree_name_ref VALUES (45,'MArch','Master of Architecture (MArch)/Master of Fine Arts (MFA)');
INSERT INTO degree_name_ref VALUES (46,'MArch','Master of Architecture (MArch)/Master of Urban Planning (MUP)');
INSERT INTO degree_name_ref VALUES (47,'MA','Master of Arts (MA)');
INSERT INTO degree_name_ref VALUES (48,'MAC','Master of Arts in Counseling (MAC)');
INSERT INTO degree_name_ref VALUES (49,'MAE','Master of Arts in Education (MAE)');
INSERT INTO degree_name_ref VALUES (50,'MAIS','Master of Arts in Interdisciplinary Studies (MAIS)');
INSERT INTO degree_name_ref VALUES (51,'MAPC','Master of Arts in Pastoral Counseling (MAPC)');
INSERT INTO degree_name_ref VALUES (52,'MAR','Master of Arts in Religion (MAR)');
INSERT INTO degree_name_ref VALUES (53,'MAT','Master of Arts in Teaching (MAT)');
INSERT INTO degree_name_ref VALUES (54,'MATE','Master of Arts in the Teaching of English (MATE)');
INSERT INTO degree_name_ref VALUES (55,'MBioSci','Master of Biological Science (MBioSci)');
INSERT INTO degree_name_ref VALUES (56,'MBS','Master of Building Science (MBS)');
INSERT INTO degree_name_ref VALUES (57,'MBA','Master of Business Administration (MBA)');
INSERT INTO degree_name_ref VALUES (58,'NULL','Master of Business Administration/Master of Science in Information Systems');
INSERT INTO degree_name_ref VALUES (59,'MBT','Master of Business Taxation (MBT)');
INSERT INTO degree_name_ref VALUES (60,'MCTE','Master of Career and Technology Education (MCTE)');
INSERT INTO degree_name_ref VALUES (61,'MChE','Master of Chemical Engineering (MChE)');
INSERT INTO degree_name_ref VALUES (62,'MCRP','Master of City and Regional Planning (MCRP)');
INSERT INTO degree_name_ref VALUES (63,'MCE','Master of Civil Engineering (MCE)');
INSERT INTO degree_name_ref VALUES (64,'NULL','Master of Community Planning');
INSERT INTO degree_name_ref VALUES (65,'MCIS','Master of Computer and Information Science (MCIS)');
INSERT INTO degree_name_ref VALUES (66,'MCompE','Master of Computer Engineering (MCompE)');
INSERT INTO degree_name_ref VALUES (67,'MCM','Master of Construction Management (MCM)');
INSERT INTO degree_name_ref VALUES (68,'MCSM','Master of Construction Science and Management (MCSM)');
INSERT INTO degree_name_ref VALUES (69,'MCJ','Master of Criminal Justice (MCJ)');
INSERT INTO degree_name_ref VALUES (70,'MDiv','Master of Divinity (MDiv)');
INSERT INTO degree_name_ref VALUES (71,'MEd','Master of Education (MEd)');
INSERT INTO degree_name_ref VALUES (72,'MEE','Master of Electrical Engineering (MEE)');
INSERT INTO degree_name_ref VALUES (73,'MECom','Master of Electronic Commerce (MECom)');
INSERT INTO degree_name_ref VALUES (74,'ME','Master of Engineering (ME)');
INSERT INTO degree_name_ref VALUES (75,'MEngr','Master of Engineering (MEngr)');
INSERT INTO degree_name_ref VALUES (76,'MEnvE','Master of Environmental Engineering (MEnvE)');
INSERT INTO degree_name_ref VALUES (77,'MES','Master of Environmental Studies (MES)');
INSERT INTO degree_name_ref VALUES (78,'MFA','Master of Fine Arts (MFA)');
INSERT INTO degree_name_ref VALUES (79,'MFR','Master of Forest Resources (MFR)');
INSERT INTO degree_name_ref VALUES (80,'MF','Master of Forestry (MF) ');
INSERT INTO degree_name_ref VALUES (81,'MGS','Master of General Studies (MGS)');
INSERT INTO degree_name_ref VALUES (82,'MGIS','Master of Geographic Information Science (MGIS)');
INSERT INTO degree_name_ref VALUES (83,'MGeoE','Master of Geomechanics Engineering (MGeoE)');
INSERT INTO degree_name_ref VALUES (84,'MHA','Master of Health Administration (MHA)');
INSERT INTO degree_name_ref VALUES (85,'MHP','Master of Historic Preservation (MHP)');
INSERT INTO degree_name_ref VALUES (86,'MHAMS','Master of Historical Administration and Museum Studies (MHAMS)');
INSERT INTO degree_name_ref VALUES (87,'MHD','Master of Human Development (MHD)');
INSERT INTO degree_name_ref VALUES (88,'MHRD','Master of Human Resource Development (MHRD)');
INSERT INTO degree_name_ref VALUES (89,'MIDS','Master of Interdisciplinary Studies (MIDS)');
INSERT INTO degree_name_ref VALUES (90,'MIM','Master of International Management (MIM)');
INSERT INTO degree_name_ref VALUES (91,'MJS','Master of Judicial Studies (MJS)');
INSERT INTO degree_name_ref VALUES (92,'MLA','Master of Landscape Architecture (MLA)');
INSERT INTO degree_name_ref VALUES (93,'MLS','Master of Library Science/Master of Life Sciences (MLS)');
INSERT INTO degree_name_ref VALUES (94,'MM','Master of Management (MM)');
INSERT INTO degree_name_ref VALUES (95,'MMatSE','Master of Materials Science and Engineering (MMatSE)');
INSERT INTO degree_name_ref VALUES (96,'MM','Master of Music (MM)');
INSERT INTO degree_name_ref VALUES (97,'MMUS','Master of Music (MMUS)');
INSERT INTO degree_name_ref VALUES (98,'MME','Master of Music Education (MME)');
INSERT INTO degree_name_ref VALUES (99,'MPRTM','Master of Parks, Recreation and Tourism Management (MPRTM)');
INSERT INTO degree_name_ref VALUES (100,'MPT','Master of Physical Therapy (MPT)');
INSERT INTO degree_name_ref VALUES (101,'MPlan','Master of Planning (MPlan)');
INSERT INTO degree_name_ref VALUES (102,'MPAcc','Master of Professional Accounting (MPAcc)');
INSERT INTO degree_name_ref VALUES (103,'MPA','Master of Public Administration (MPA)');
INSERT INTO degree_name_ref VALUES (104,'MPA/JD','Master of Public Administration/Juris Doctorate (MPA/JD)');
INSERT INTO degree_name_ref VALUES (105,'MPH','Master of Public Health (MPH)');
INSERT INTO degree_name_ref VALUES (106,'MPM','Master of Public Management (MPM)');
INSERT INTO degree_name_ref VALUES (107,'MPP','Master of Public Policy (MPP)');
INSERT INTO degree_name_ref VALUES (108,'MRED','Master of Real Estate Development (MRED)');
INSERT INTO degree_name_ref VALUES (109,'MRP','Master of Regional Planning (MRP)');
INSERT INTO degree_name_ref VALUES (110,'MSA','Master of School Administration (MSA)');
INSERT INTO degree_name_ref VALUES (111,'MS','Master of Science (MS)');
INSERT INTO degree_name_ref VALUES (112,'MSSE','Master of Science and Software Engineering (MSSE)');
INSERT INTO degree_name_ref VALUES (113,'MSA','Master of Science in Acountancy (MSA)');
INSERT INTO degree_name_ref VALUES (114,'MSA','Master of Science in Administration (MSA)');
INSERT INTO degree_name_ref VALUES (115,'MSAeroE','Master of Science in Aerospace Engineering (MSAeroE)');
INSERT INTO degree_name_ref VALUES (116,'MSAgE','Master of Science in Agricultural Engineering (MSAgE)');
INSERT INTO degree_name_ref VALUES (117,'NULL','Master of Science in Biomedical Engineering');
INSERT INTO degree_name_ref VALUES (118,'MSBiosyAgE','Master of Science in Biosystems and Agricultural Engineering (MSBiosyAgE)');
INSERT INTO degree_name_ref VALUES (119,'MSChE','Master of Science in Chemical Engineering (MSChE)');
INSERT INTO degree_name_ref VALUES (120,'MSCE','Master of Science in Civil Engineering (MSCE)');
INSERT INTO degree_name_ref VALUES (121,'MSCRP','Master of Science in Community and Regional Planning (MSCRP)');
INSERT INTO degree_name_ref VALUES (122,'MSECO','Master of Science in Economics (MSECO)');
INSERT INTO degree_name_ref VALUES (123,'MSEd','Master of Science in Education (MSEd)');
INSERT INTO degree_name_ref VALUES (124,'MSECE','Master of Science in Electrical and Computer Engineering (MSECE)');
INSERT INTO degree_name_ref VALUES (125,'MSEE','Master of Science in Electrical Engineering (MSEE)');
INSERT INTO degree_name_ref VALUES (126,'MSE','Master of Science in Engineering (MSE)');
INSERT INTO degree_name_ref VALUES (127,'MSEM','Master of Science in Engineering Management (MSEM)');
INSERT INTO degree_name_ref VALUES (128,'MSETM','Master of Science in Environmental Technology Management (MSETM)');
INSERT INTO degree_name_ref VALUES (129,'MSHTM','Master of Science in Hospitality and Tourism Management (MSHTM)');
INSERT INTO degree_name_ref VALUES (130,'MSHRM','Master of Science in Human Resources Management (MSHRM)');
INSERT INTO degree_name_ref VALUES (131,'MSIE','Master of Science in Industrial Engineering (MSIE)');
INSERT INTO degree_name_ref VALUES (132,'MSIEOR','Master of Science in Industrial Engineering and Operations Research (MSIEOR)');
INSERT INTO degree_name_ref VALUES (133,'MSIS','Master of Science in Information Systems (MSIS)');
INSERT INTO degree_name_ref VALUES (134,'MSISE','Master of Science in Infrastructure Systems Engineering (MSISE)');
INSERT INTO degree_name_ref VALUES (135,'MSIS','Master of Science in Interdisciplinary Studies (MSIS)');
INSERT INTO degree_name_ref VALUES (136,'MSIB','Master of Science in International Business (MSIB)');
INSERT INTO degree_name_ref VALUES (137,'MSJ','Master of Science in Jurisprudence (MSJ)');
INSERT INTO degree_name_ref VALUES (138,'MSM','Master of Science in Management (MSM)');
INSERT INTO degree_name_ref VALUES (139,'MSMANFE','Master of Science in Manufacturing Engineering (MSMANFE)');
INSERT INTO degree_name_ref VALUES (140,'MSMatSE','Master of Science in Material Science Engineering (MSMatSE)');
INSERT INTO degree_name_ref VALUES (141,'MSMSE','Master of Science in Materials Science and Engineering (MSMSE)');
INSERT INTO degree_name_ref VALUES (142,'MSME','Master of Science in Mechanical Engineering (MSME)');
INSERT INTO degree_name_ref VALUES (143,'MSMS','Master of Science in Medical Sciences (MSMS)');
INSERT INTO degree_name_ref VALUES (144,'MSN','Master of Science in Nursing (MSN)');
INSERT INTO degree_name_ref VALUES (145,'MSPE','Master of Science in Petroleum Engineering (MSPE)');
INSERT INTO degree_name_ref VALUES (146,'MSP','Master of Science in Planning (MSP)');
INSERT INTO degree_name_ref VALUES (147,'MSPH','Master of Science in Public Health (MSPH)');
INSERT INTO degree_name_ref VALUES (148,'MSW','Master of Social Welfare (MSW)');
INSERT INTO degree_name_ref VALUES (149,'MSW','Master of Social Work (MSW)');
INSERT INTO degree_name_ref VALUES (150,'MTS','Master of Theological Studies (MTS)');
INSERT INTO degree_name_ref VALUES (151,'ThM','Master of Theology (ThM)');
INSERT INTO degree_name_ref VALUES (152,'MURP','Master of Urban and Regional Planning (MURP)');
INSERT INTO degree_name_ref VALUES (153,'MUP','Master of Urban Planning (MUP)');
INSERT INTO degree_name_ref VALUES (154,'MHI','Master of Health Informatics (MHI)');
INSERT INTO degree_name_ref VALUES (155,'MSB','Master of Science in Bioscience (MSB)');
INSERT INTO degree_name_ref VALUES (156,'MST','Master of Science in Teaching (MST)');
INSERT INTO degree_name_ref VALUES (157,'MD','Medical Doctor (MD)');
INSERT INTO degree_name_ref VALUES (158,'MSExpSurg','Medical Surgeon in Experimental Surgery (MSExpSurg)');
INSERT INTO degree_name_ref VALUES (159,'MSOtol','MS Otolaryngology (MSOtol)');
INSERT INTO degree_name_ref VALUES (160,'PhDOtol','PhD Otolaryngology (PhDOtol)');
INSERT INTO degree_name_ref VALUES (161,'PhDSurg','PhD Surgery (PhDSurg)');
INSERT INTO degree_name_ref VALUES (162,'PMBA','Professional Master of Business Administration (PMBA)');
