USE etd;

CREATE TABLE IF NOT EXISTS discipline_ref (
    discipline_id INT(10) UNSIGNED NOT NULL,
    discipline_name VARCHAR(100) NOT NULL,
    PRIMARY KEY (discipline_id));

INSERT INTO discipline_ref (discipline_id, discipline_name) VALUES
(1, 'Architecture'),
(2, 'Architectural Engineering'),
(3, 'Architectural History and Criticism'),
(4, 'Architectural Technology'),
(5, 'Construction Engineering'),
(6, 'Cultural Resource Management and Policy Analysis'),
(7, 'Environmental Design'),
(8, 'Historic Preservation and Conservation'),
(9, 'Interior Architecture'),
(10, 'Landscape Architecture'),
(11, 'Urban, Community and Regional Planning'),
(12, 'Other Architecture'),
(13, 'Arts and Humanities'),
(14, 'African Languages and Societies'),
(15, 'American Studies'),
(16, 'American Film Studies'),
(17, 'American Literature'),
(18, 'American Material Culture'),
(19, 'American Popular Culture'),
(20, 'Other American Studies'),
(21, 'Appalachian Studies'),
(22, 'Art and Design'),
(23, 'Art and Materials Conservation'),
(24, 'Book and Paper'),
(25, 'Ceramic Arts'),
(26, 'Fashion Design'),
(27, 'Fiber, Textile, and Weaving Arts'),
(28, 'Game Design'),
(29, 'Graphic Design'),
(30, 'Illustration'),
(31, 'Industrial and Product Design'),
(32, 'Interactive Arts'),
(33, 'Interdisciplinary Arts and Media'),
(34, 'Metal and Jewelry Arts'),
(35, 'Painting'),
(36, 'Printmaking'),
(37, 'Sculpture'),
(38, 'Art Practice'),
(39, 'Audio Arts and Acoustics'),
(40, 'Australian Studies'),
(41, 'Basque Studies'),
(42, 'Celtic Studies'),
(43, 'Classics'),
(44, 'Ancient History, Greek and Roman through Late Antiquity'),
(45, 'Ancient Philosophy'),
(46, 'Byzantine and Modern Greek'),
(47, 'Classical Archaeology and Art History'),
(48, 'Classical Literature and Philology'),
(49, 'Indo-European Linguistics and Philology'),
(50, 'Other Classics'),
(51, 'Comparative Literature'),
(52, 'Translation Studies'),
(53, 'Creative Writing'),
(54, 'Fiction'),
(55, 'Nonfiction'),
(56, 'Poetry'),
(57, 'Digital Humanities'),
(58, 'Dutch Studies'),
(59, 'East Asian Languages and Societies'),
(60, 'Chinese Studies'),
(61, 'Japanese Studies'),
(62, 'Korean Studies'),
(63, 'English Language and Literature'),
(64, 'Children\'s and Young Adult Literature'),
(65, 'Literature in English, Anglophone outside British Isles and North America'),
(66, 'Literature in English, British Isles'),
(67, 'Literature in English, North America'),
(68, 'Literature in English, North America, Ethnic and Cultural Minority'),
(69, 'Other English Language and Literature'),
(70, 'European Languages and Societies'),
(71, 'Feminist, Gender, and Sexuality Studies'),
(72, 'Lesbian, Gay, Bisexual, and Transgender Studies'),
(73, 'Women\'s Studies'),
(74, 'Other Feminist, Gender, and Sexuality Studies'),
(75, 'Film and Media Studies'),
(76, 'Film Production'),
(77, 'Screenwriting'),
(78, 'Visual Studies'),
(79, 'Other Film and Media Studies'),
(80, 'Fine Arts'),
(81, 'French and Francophone Language and Literature'),
(82, 'French and Francophone Literature'),
(83, 'French Linguistics'),
(84, 'Other French and Francophone Language and Literature'),
(85, 'German Language and Literature'),
(86, 'German Linguistics'),
(87, 'German Literature'),
(88, 'Other German Language and Literature'),
(89, 'History'),
(90, 'African History'),
(91, 'Asian History'),
(92, 'Canadian History'),
(93, 'Cultural History'),
(94, 'Diplomatic History'),
(95, 'European History'),
(96, 'Genealogy'),
(97, 'History of Gender'),
(98, 'History of the Pacific Islands'),
(99, 'History of Religion'),
(100, 'History of Science, Technology, and Medicine'),
(101, 'Intellectual History'),
(102, 'Islamic World and Near East History'),
(103, 'Labor History'),
(104, 'Latin American History'),
(105, 'Legal'),
(106, 'Medieval History'),
(107, 'Military History'),
(108, 'Oral History'),
(109, 'Political History'),
(110, 'Public History'),
(111, 'Social History'),
(112, 'United States History'),
(113, 'Women\'s History'),
(114, 'Other History'),
(115, 'History of Art, Architecture, and Archaeology'),
(116, 'American Art and Architecture'),
(117, 'Ancient, Medieval, Renaissance and Baroque Art and Architecture'),
(118, 'Asian Art and Architecture'),
(119, 'Contemporary Art'),
(120, 'Modern Art and Architecture'),
(121, 'Theory and Criticism'),
(122, 'Other History of Art, Architecture, and Archaeology'),
(123, 'Italian Language and Literature'),
(124, 'Italian Linguistics'),
(125, 'Italian Literature'),
(126, 'Other Italian Language and Literature'),
(127, 'Jewish Studies'),
(128, 'Yiddish Language and Literature'),
(129, 'Latin American Languages and Societies'),
(130, 'Caribbean Languages and Societies'),
(131, 'Medieval Studies'),
(132, 'Modern Languages'),
(133, 'Modern Literature'),
(134, 'Museum Studies'),
(135, 'Music'),
(136, 'Composition'),
(137, 'Ethnomusicology'),
(138, 'Music Education'),
(139, 'Music Practice'),
(140, 'Music Theory'),
(141, 'Musicology'),
(142, 'Music Pedagogy'),
(143, 'Music Performance'),
(144, 'Music Therapy'),
(145, 'Other Music'),
(146, 'Near Eastern Languages and Societies'),
(147, 'Pacific Islands Languages and Societies'),
(148, 'Hawaiian Studies'),
(149, 'Melanesian Studies'),
(150, 'Micronesian Studies'),
(151, 'Polynesian Studies'),
(152, 'Philosophy'),
(153, 'Comparative Philosophy'),
(154, 'Continental Philosophy'),
(155, 'Epistemology'),
(156, 'Esthetics'),
(157, 'Ethics and Political Philosophy'),
(158, 'Feminist Philosophy'),
(159, 'History of Philosophy'),
(160, 'Logic and Foundations of Mathematics'),
(161, 'Metaphysics'),
(162, 'Philosophy of Language'),
(163, 'Philosophy of Mind'),
(164, 'Philosophy of Science'),
(165, 'Other Philosophy'),
(166, 'Photography'),
(167, 'Race, Ethnicity and Post-Colonial Studies'),
(168, 'African American Studies'),
(169, 'Asian American Studies'),
(170, 'Chicana/o Studies'),
(171, 'Ethnic Studies'),
(172, 'Indigenous Studies'),
(173, 'Latina/o Studies'),
(174, 'Radio'),
(175, 'Reading and Language'),
(176, 'Religion'),
(177, 'Biblical Studies'),
(178, 'Buddhist Studies'),
(179, 'Catholic Studies'),
(180, 'Christianity'),
(181, 'Christian Denominations and Sects'),
(182, 'Comparative Methodologies and Theories'),
(183, 'Ethics in Religion'),
(184, 'Hindu Studies'),
(185, 'History of Christianity'),
(186, 'History of Religions of Eastern Origins'),
(187, 'History of Religions of Western Origin'),
(188, 'Islamic Studies'),
(189, 'Liturgy and Worship'),
(190, 'Missions and World Christianity'),
(191, 'Mormon Studies'),
(192, 'New Religious Movements'),
(193, 'Practical Theology'),
(194, 'Religious Thought, Theology and Philosophy of Religion'),
(195, 'Other Religion'),
(196, 'Rhetoric and Composition'),
(197, 'Rhetoric'),
(198, 'Other Rhetoric and Composition'),
(199, 'Scandinavian Studies'),
(200, 'Slavic Languages and Societies'),
(201, 'Russian Linguistics'),
(202, 'Russian Literature'),
(203, 'South and Southeast Asian Languages and Societies'),
(204, 'Spanish and Portuguese Language and Literature'),
(205, 'Latin American Literature'),
(206, 'Portuguese Literature'),
(207, 'Spanish Linguistics'),
(208, 'Spanish Literature'),
(209, 'Other Spanish and Portuguese Language and Literature'),
(210, 'Technical and Professional Writing'),
(211, 'Television'),
(212, 'Theatre and Performance Studies'),
(213, 'Acting'),
(214, 'Dance'),
(215, 'Dramatic Literature, Criticism and Theory'),
(216, 'Performance Studies'),
(217, 'Playwriting'),
(218, 'Theatre History'),
(219, 'Other Theatre and Performance Studies'),
(220, 'Other Arts and Humanities'),
(221, 'Other Languages, Societies, and Cultures'),
(222, 'Business'),
(223, 'Accounting'),
(224, 'Advertising and Promotion Management'),
(225, 'Agribusiness'),
(226, 'Arts Management'),
(227, 'Business Administration, Management, and Operations'),
(228, 'Business and Corporate Communications'),
(229, 'Business Intelligence'),
(230, 'Business Law, Public Responsibility, and Ethics'),
(231, 'Corporate Finance'),
(232, 'E-Commerce'),
(233, 'Entrepreneurial and Small Business Operations'),
(234, 'Fashion Business'),
(235, 'Finance and Financial Management'),
(236, 'Hospitality Administration and Management'),
(237, 'Food and Beverage Management'),
(238, 'Gaming and Casino Operations Management'),
(239, 'Human Resources Management'),
(240, 'Benefits and Compensation'),
(241, 'Performance Management'),
(242, 'Training and Development'),
(243, 'Insurance'),
(244, 'International Business'),
(245, 'Labor Relations'),
(246, 'Collective Bargaining'),
(247, 'International and Comparative Labor Relations'),
(248, 'Unions'),
(249, 'Management Information Systems'),
(250, 'Management Sciences and Quantitative Methods'),
(251, 'Marketing'),
(252, 'Art Direction'),
(253, 'Nonprofit Administration and Management'),
(254, 'Operations and Supply Chain Management'),
(255, 'Organizational Behavior and Theory'),
(256, 'Portfolio and Security Analysis'),
(257, 'Real Estate'),
(258, 'Recreation Business'),
(259, 'Sales and Merchandising'),
(260, 'Sports Management'),
(261, 'Strategic Management Policy'),
(262, 'Taxation'),
(263, 'Technology and Innovation'),
(264, 'Tourism and Travel'),
(265, 'Other Business'),
(266, 'Education'),
(267, 'Adult and Continuing Education'),
(268, 'Art Education'),
(269, 'Bilingual, Multilingual, and Multicultural Education'),
(270, 'Community College Leadership'),
(271, 'Curriculum and Instruction'),
(272, 'Curriculum and Social Inquiry'),
(273, 'Disability and Equity in Education'),
(274, 'Accessibility'),
(275, 'Gender Equity in Education'),
(276, 'Early Childhood Education'),
(277, 'Education Economics'),
(278, 'Educational Administration and Supervision'),
(279, 'Adult and Continuing Education Administration'),
(280, 'Community College Education Administration'),
(281, 'Elementary and Middle and Secondary Education Administration'),
(282, 'Higher Education Administration'),
(283, 'Special Education Administration'),
(284, 'Urban Education'),
(285, 'Other Educational Administration and Supervision'),
(286, 'Educational Assessment, Evaluation, and Research'),
(287, 'Educational Leadership'),
(288, 'Educational Methods'),
(289, 'Educational Psychology'),
(290, 'Elementary Education'),
(291, 'Gifted Education'),
(292, 'Health and Physical Education'),
(293, 'Higher Education'),
(294, 'Scholarship of Teaching and Learning'),
(295, 'University Extension'),
(296, 'Home Economics'),
(297, 'Humane Education'),
(298, 'Indigenous Education'),
(299, 'Instructional Media Design'),
(300, 'International and Comparative Education'),
(301, 'Language and Literacy Education'),
(302, 'Liberal Studies'),
(303, 'Online and Distance Education'),
(304, 'Outdoor Education'),
(305, 'Science and Mathematics Education'),
(306, 'Secondary Education'),
(307, 'Social and Philosophical Foundations of Education'),
(308, 'Special Education and Teaching'),
(309, 'Student Counseling and Personnel Services'),
(310, 'Teacher Education and Professional Development'),
(311, 'Adult and Continuing Education and Teaching'),
(312, 'Elementary Education and Teaching'),
(313, 'Higher Education and Teaching'),
(314, 'Junior High, Intermediate, Middle School'),
(315, 'Education and Teaching'),
(316, 'Pre-Elementary, Early Childhood, Kindergarten Teacher Education'),
(317, 'Secondary Education and Teaching'),
(318, 'Other Teacher Education and Professional Development'),
(319, 'Other Education'),
(320, 'Vocational Education'),
(321, 'Engineering'),
(322, 'Aerospace Engineering'),
(323, 'Aerodynamics and Fluid Mechanics'),
(324, 'Aeronautical Vehicles'),
(325, 'Astrodynamics'),
(326, 'Multi-Vehicle Systems and Air Traffic Control'),
(327, 'Navigation, Guidance, Control and Dynamics'),
(328, 'Propulsion and Power'),
(329, 'Space Vehicles'),
(330, 'Structures and Materials'),
(331, 'Systems Engineering and Multidisciplinary Design Optimization'),
(332, 'Other Aerospace Engineering'),
(333, 'Automotive Engineering'),
(334, 'Aviation'),
(335, 'Aviation and Space Education'),
(336, 'Aviation Safety and Security'),
(337, 'Maintenance Technology'),
(338, 'Management and Operations'),
(339, 'Biomedical Engineering and Bioengineering'),
(340, 'Bioelectrical and Neuroengineering'),
(341, 'Bioimaging and Biomedical Optics'),
(342, 'Biological Engineering'),
(343, 'Biomaterials'),
(344, 'Biomechanics and Biotransport'),
(345, 'Biomedical Devices and Instrumentation'),
(346, 'Molecular, Cellular, and Tissue Engineering'),
(347, 'Systems and Integrative Engineering'),
(348, 'Vision Science'),
(349, 'Other Biomedical Engineering and Bioengineering'),
(350, 'Bioresource and Agricultural Engineering'),
(351, 'Chemical Engineering'),
(352, 'Biochemical and Biomolecular Engineering'),
(353, 'Catalysis and Reaction Engineering'),
(354, 'Complex Fluids'),
(355, 'Membrane Science'),
(356, 'Petroleum Engineering'),
(357, 'Polymer Science'),
(358, 'Process Control and Systems'),
(359, 'Thermodynamics'),
(360, 'Transport Phenomena'),
(361, 'Other Chemical Engineering'),
(362, 'Civil and Environmental Engineering'),
(363, 'Civil Engineering'),
(364, 'Construction Engineering and Management'),
(365, 'Environmental Engineering'),
(366, 'Geotechnical Engineering'),
(367, 'Hydraulic Engineering'),
(368, 'Structural Engineering'),
(369, 'Transportation Engineering'),
(370, 'Other Civil and Environmental Engineering'),
(371, 'Computational Engineering'),
(372, 'Computer Engineering'),
(373, 'Computer and Systems Architecture'),
(374, 'Data Storage Systems'),
(375, 'Digital Circuits'),
(376, 'Digital Communications and Networking'),
(377, 'Hardware Systems'),
(378, 'Robotics'),
(379, 'Other Computer Engineering'),
(380, 'Electrical and Computer Engineering'),
(381, 'Biomedical'),
(382, 'Controls and Control Theory'),
(383, 'Electrical and Electronics'),
(384, 'Electromagnetics and Photonics'),
(385, 'Electronic Devices and Semiconductor Manufacturing'),
(386, 'Nanotechnology Fabrication'),
(387, 'Power and Energy'),
(388, 'Signal Processing'),
(389, 'Systems and Communications'),
(390, 'VLSI and Circuits, Embedded and Hardware Systems'),
(391, 'Other Electrical and Computer Engineering'),
(392, 'Engineering Education'),
(393, 'Engineering Science and Materials'),
(394, 'Dynamics and Dynamical Systems'),
(395, 'Engineering Mechanics'),
(396, 'Mechanics of Materials'),
(397, 'Other Engineering Science and Materials'),
(398, 'Materials Science and Engineering'),
(399, 'Biology and Biomimetic Materials'),
(400, 'Ceramic Materials'),
(401, 'Metallurgy'),
(402, 'Polymer and Organic Materials'),
(403, 'Semiconductor and Optical Materials'),
(404, 'Structural Materials'),
(405, 'Other Materials Science and Engineering'),
(406, 'Mechanical Engineering'),
(407, 'Acoustics, Dynamics, and Controls'),
(408, 'Applied Mechanics'),
(409, 'Biomechanical Engineering'),
(410, 'Computer-Aided Engineering and Design'),
(411, 'Electro-Mechanical Systems'),
(412, 'Energy Systems'),
(413, 'Heat Transfer, Combustion'),
(414, 'Manufacturing'),
(415, 'Ocean Engineering'),
(416, 'Tribology'),
(417, 'Other Mechanical Engineering'),
(418, 'Mining Engineering'),
(419, 'Nanoscience and Nanotechnology'),
(420, 'Nuclear Engineering'),
(421, 'Operations Research, Systems Engineering and Industrial Engineering'),
(422, 'Ergonomics'),
(423, 'Industrial'),
(424, 'Engineering'),
(425, 'Industrial Technology'),
(426, 'Operational Research'),
(427, 'Systems Engineering'),
(428, 'Other Operations'),
(429, 'Research, Systems Engineering and Industrial Engineering'),
(430, 'Risk Analysis'),
(431, 'Other Engineering'),
(432, 'Law'),
(433, 'Accounting Law'),
(434, 'Administrative Law'),
(435, 'Admiralty'),
(436, 'Agency'),
(437, 'Agriculture Law'),
(438, 'Air and Space Law'),
(439, 'Animal Law'),
(440, 'Antitrust and Trade Regulation'),
(441, 'Banking and Finance Law'),
(442, 'Bankruptcy Law'),
(443, 'Business Organizations Law'),
(444, 'Civil Law'),
(445, 'Civil Procedure'),
(446, 'Civil Rights and Discrimination'),
(447, 'Commercial Law'),
(448, 'Common Law'),
(449, 'Communications Law'),
(450, 'Comparative and Foreign Law'),
(451, 'Computer Law'),
(452, 'Conflict of Laws'),
(453, 'Constitutional Law'),
(454, 'Construction Law'),
(455, 'Consumer Protection Law'),
(456, 'Contracts'),
(457, 'Courts'),
(458, 'Criminal Law'),
(459, 'Criminal Procedure'),
(460, 'Cultural Heritage Law'),
(461, 'Disability Law'),
(462, 'Disaster Law'),
(463, 'Dispute Resolution and Arbitration'),
(464, 'Education Law'),
(465, 'Elder Law'),
(466, 'Election Law'),
(467, 'Energy and Utilities Law'),
(468, 'Entertainment, Arts, and Sports Law'),
(469, 'Environmental Law'),
(470, 'Estates and Trusts'),
(471, 'European Law'),
(472, 'Evidence'),
(473, 'Family Law'),
(474, 'First Amendment'),
(475, 'Food and Drug Law'),
(476, 'Fourteenth Amendment'),
(477, 'Fourth Amendment'),
(478, 'Gaming Law'),
(479, 'Government Contracts'),
(480, 'Health Law and Policy'),
(481, 'Housing Law'),
(482, 'Human Rights Law'),
(483, 'Immigration Law'),
(484, 'Indian and Aboriginal Law'),
(485, 'Insurance Law'),
(486, 'Intellectual Property Law'),
(487, 'International Humanitarian Law'),
(488, 'International Law'),
(489, 'International Trade Law'),
(490, 'Internet Law'),
(491, 'Judges'),
(492, 'Jurisdiction'),
(493, 'Jurisprudence'),
(494, 'Juvenile Law'),
(495, 'Labor and Employment Law'),
(496, 'Land Use Law'),
(497, 'Law and Economics'),
(498, 'Law and Gender'),
(499, 'Law and Philosophy'),
(500, 'Law and Politics'),
(501, 'Law and Psychology'),
(502, 'Law and Race'),
(503, 'Law and Society'),
(504, 'Law Enforcement and Corrections'),
(505, 'Law of the Sea'),
(506, 'Legal Biography'),
(507, 'Legal Education'),
(508, 'Legal Ethics and Professional Responsibility'),
(509, 'Legal History'),
(510, 'Legal Profession'),
(511, 'Legal Remedies'),
(512, 'Legal Writing and Research'),
(513, 'Legislation'),
(514, 'Litigation'),
(515, 'Marketing Law'),
(516, 'Medical Jurisprudence'),
(517, 'Military, War, and Peace'),
(518, 'National Security Law'),
(519, 'Natural Law'),
(520, 'Natural Resources Law'),
(521, 'Nonprofit Organizations Law'),
(522, 'Oil, Gas, and Mineral Law'),
(523, 'Organizations Law'),
(524, 'President/Executive Department'),
(525, 'Privacy Law'),
(526, 'Property Law and Real Estate'),
(527, 'Public Law and Legal Theory'),
(528, 'Religion Law'),
(529, 'Retirement Security Law'),
(530, 'Rule of Law'),
(531, 'Science and Technology Law'),
(532, 'Second Amendment'),
(533, 'Secured Transactions'),
(534, 'Securities Law'),
(535, 'Sexuality and the Law'),
(536, 'Social Welfare Law'),
(537, 'State and Local Government Law'),
(538, 'Supreme Court of the United States'),
(539, 'Tax Law'),
(540, 'Taxation-Federal'),
(541, 'Taxation-Federal Estate and Gift'),
(542, 'Taxation-State and Local'),
(543, 'Taxation-Transnational'),
(544, 'Torts'),
(545, 'Transnational Law'),
(546, 'Transportation Law'),
(547, 'Water Law'),
(548, 'Workers\' Compensation Law'),
(549, 'Other Law'),
(550, 'Life Sciences'),
(551, 'Agriculture'),
(552, 'Agricultural Economics'),
(553, 'Agricultural Education'),
(554, 'Apiculture'),
(555, 'Biosecurity'),
(556, 'Viticulture and Oenology'),
(557, 'Animal Sciences'),
(558, 'Aquaculture and Fisheries'),
(559, 'Dairy Science'),
(560, 'Meat Science'),
(561, 'Ornithology'),
(562, 'Poultry or Avian Science'),
(563, 'Sheep and Goat Science'),
(564, 'Zoology'),
(565, 'Other Animal Sciences'),
(566, 'Biochemistry, Biophysics, and Structural Biology'),
(567, 'Biochemistry'),
(568, 'Biophysics'),
(569, 'Molecular Biology'),
(570, 'Structural Biology'),
(571, 'Other Biochemistry, Biophysics, and Structural Biology'),
(572, 'Biodiversity'),
(573, 'Bioinformatics'),
(574, 'Biology'),
(575, 'Integrative Biology'),
(576, 'Biotechnology'),
(577, 'Cell and Developmental Biology'),
(578, 'Cancer Biology'),
(579, 'Cell Anatomy'),
(580, 'Cell Biology'),
(581, 'Developmental Biology'),
(582, 'Other Cell and Developmental Biology'),
(583, 'Ecology and Evolutionary Biology'),
(584, 'Behavior and Ethology'),
(585, 'Desert Ecology'),
(586, 'Evolution'),
(587, 'Population Biology'),
(588, 'Terrestrial and Aquatic Ecology'),
(589, 'Other Ecology and Evolutionary Biology'),
(590, 'Entomology'),
(591, 'Food Science'),
(592, 'Food Biotechnology'),
(593, 'Food Chemistry'),
(594, 'Food Microbiology'),
(595, 'Food Processing'),
(596, 'Other Food Science'),
(597, 'Forest Sciences'),
(598, 'Forest Biology'),
(599, 'Forest Management'),
(600, 'Wood Science and Pulp, Paper Technology'),
(601, 'Other Forestry and Forest Sciences'),
(602, 'Genetics and Genomics'),
(603, 'Computational Biology'),
(604, 'Genetics'),
(605, 'Genomics'),
(606, 'Molecular Genetics'),
(607, 'Other Genetics and Genomics'),
(608, 'Immunology and Infectious Disease'),
(609, 'Immunity'),
(610, 'Immunology of Infectious Disease'),
(611, 'Immunopathology'),
(612, 'Immunoprophylaxis and Therapy'),
(613, 'Parasitology'),
(614, 'Other Immunology and Infectious Disease'),
(615, 'Kinesiology'),
(616, 'Biomechanics'),
(617, 'Exercise Science'),
(618, 'Expeditionary Education'),
(619, 'Motor Control'),
(620, 'Psychology of Movement'),
(621, 'Other Kinesiology'),
(622, 'Laboratory and Basic Science Research'),
(623, 'Marine Biology'),
(624, 'Microbiology'),
(625, 'Bacteriology'),
(626, 'Environmental Microbiology and Microbial Ecology'),
(627, 'Microbial Physiology'),
(628, 'Organismal Biological Physiology'),
(629, 'Pathogenic Microbiology'),
(630, 'Virology'),
(631, 'Other Microbiology'),
(632, 'Neuroscience and Neurobiology'),
(633, 'Behavioral Neurobiology'),
(634, 'Cognitive Neuroscience'),
(635, 'Computational Neuroscience'),
(636, 'Developmental Neuroscience'),
(637, 'Molecular and Cellular Neuroscience'),
(638, 'Systems Neuroscience'),
(639, 'Other Neuroscience and Neurobiology'),
(640, 'Nutrition'),
(641, 'Comparative Nutrition'),
(642, 'Human and Clinical Nutrition'),
(643, 'International and Community Nutrition'),
(644, 'Molecular, Genetic, and Biochemical Nutrition'),
(645, 'Nutritional Epidemiology'),
(646, 'Other Nutrition'),
(647, 'Pharmacology, Toxicology and Environmental Health'),
(648, 'Environmental Health'),
(649, 'Medicinal Chemistry and Pharmaceutics'),
(650, 'Pharmacology'),
(651, 'Toxicology'),
(652, 'Other Pharmacology, Toxicology and Environmental Health'),
(653, 'Physiology'),
(654, 'Cellular and Molecular Physiology'),
(655, 'Comparative and Evolutionary Physiology'),
(656, 'Endocrinology'),
(657, 'Exercise Physiology'),
(658, 'Systems and Integrative Physiology'),
(659, 'Other Physiology'),
(660, 'Plant Sciences'),
(661, 'Agricultural Science'),
(662, 'Agronomy and Crop Sciences'),
(663, 'Botany'),
(664, 'Bryology'),
(665, 'Fruit Science'),
(666, 'Horticulture'),
(667, 'Plant Biology'),
(668, 'Plant Breeding and Genetics'),
(669, 'Plant Pathology'),
(670, 'Weed Science'),
(671, 'Other Plant Sciences'),
(672, 'Research Methods in Life Sciences'),
(673, 'Animal Experimentation and Research'),
(674, 'Systems Biology'),
(675, 'Other Life Sciences'),
(676, 'Medicine and Health Sciences'),
(677, 'Alternative and Complementary Medicine'),
(678, 'Analytical, Diagnostic and Therapeutic Techniques and Equipment'),
(679, 'Anesthesia and Analgesia'),
(680, 'Diagnosis'),
(681, 'Equipment and Supplies'),
(682, 'Investigative Techniques'),
(683, 'Surgical Procedures, Operative'),
(684, 'Therapeutics'),
(685, 'Other Analytical, Diagnostic and Therapeutic Techniques and Equipment'),
(686, 'Anatomy'),
(687, 'Animal Structures'),
(688, 'Body Regions'),
(689, 'Cardiovascular System'),
(690, 'Cells'),
(691, 'Digestive System'),
(692, 'Embryonic Structures'),
(693, 'Endocrine System'),
(694, 'Fluids and Secretions'),
(695, 'Hemic and Immune Systems'),
(696, 'Integumentary System'),
(697, 'Musculoskeletal System'),
(698, 'Nervous System'),
(699, 'Respiratory System'),
(700, 'Sense Organs'),
(701, 'Stomatognathic System'),
(702, 'Tissues'),
(703, 'Urogenital System'),
(704, 'Bioethics and Medical Ethics'),
(705, 'Chemicals and Drugs'),
(706, 'Amino Acids, Peptides, and Proteins'),
(707, 'Biological Factors'),
(708, 'Biomedical and Dental Materials'),
(709, 'Carbohydrates'),
(710, 'Chemical Actions and Uses'),
(711, 'Complex Mixtures'),
(712, 'Enzymes and Coenzymes'),
(713, 'Heterocyclic Compounds'),
(714, 'Hormones, Hormone Substitutes, and Hormone Antagonists'),
(715, 'Inorganic Chemicals'),
(716, 'Lipids'),
(717, 'Macromolecular Substances'),
(718, 'Nucleic Acids, Nucleotides, and Nucleosides'),
(719, 'Organic Chemicals'),
(720, 'Pharmaceutical Preparations'),
(721, 'Polycyclic Compounds'),
(722, 'Other Chemicals and Drugs'),
(723, 'Communication Sciences and Disorders'),
(724, 'Speech and Hearing Science'),
(725, 'Speech Pathology and Audiology'),
(726, 'Dentistry'),
(727, 'Dental Hygiene'),
(728, 'Dental Materials'),
(729, 'Dental Public Health and Education'),
(730, 'Endodontics and Endodontology'),
(731, 'Oral and Maxillofacial Surgery'),
(732, 'Oral Biology and Oral Pathology'),
(733, 'Orthodontics and Orthodontology'),
(734, 'Pediatric Dentistry and Pedodontics'),
(735, 'Periodontics and Periodontology'),
(736, 'Prosthodontics and Prosthodontology'),
(737, 'Other Dentistry'),
(738, 'Dietetics and Clinical Nutrition'),
(739, 'Diseases'),
(740, 'Animal Diseases'),
(741, 'Bacterial Infections and Mycoses'),
(742, 'Cardiovascular Diseases'),
(743, 'Congenital, Hereditary, and Neonatal Diseases and Abnormalities'),
(744, 'Digestive System Diseases'),
(745, 'Disease Modeling'),
(746, 'Disorders of Environmental Origin'),
(747, 'Endocrine System Diseases'),
(748, 'Eye Diseases'),
(749, 'Female Urogenital Diseases and Pregnancy Complications'),
(750, 'Hemic and Lymphatic Diseases'),
(751, 'Immune System Diseases'),
(752, 'Male Urogenital Diseases'),
(753, 'Musculoskeletal Diseases'),
(754, 'Neoplasms'),
(755, 'Nervous System Diseases'),
(756, 'Nutritional and Metabolic Diseases'),
(757, 'Otorhinolaryngologic Diseases'),
(758, 'Parasitic Diseases'),
(759, 'Pathological Conditions, Signs and Symptoms'),
(760, 'Respiratory Tract Diseases'),
(761, 'Skin and Connective Tissue Diseases'),
(762, 'Stomatognathic Diseases'),
(763, 'Virus Diseases'),
(764, 'Health Information Technology'),
(765, 'Telemedicine'),
(766, 'Health and Medical Administration'),
(767, 'Medical Education'),
(768, 'Interprofessional Education'),
(769, 'Medical Humanities'),
(770, 'Medical Sciences'),
(771, 'Biochemical Phenomena, Metabolism, and Nutrition'),
(772, 'Biological Phenomena, Cell Phenomena, and Immunity'),
(773, 'Chemical and Pharmacologic Phenomena'),
(774, 'Circulatory and Respiratory Physiology'),
(775, 'Digestive, Oral, and Skin Physiology'),
(776, 'Genetic Phenomena'),
(777, 'Genetic Processes'),
(778, 'Genetic Structures'),
(779, 'Medical Anatomy'),
(780, 'Medical Biochemistry'),
(781, 'Medical Biomathematics and Biometrics'),
(782, 'Medical Biophysics'),
(783, 'Medical Biotechnology'),
(784, 'Medical Cell Biology'),
(785, 'Medical Genetics'),
(786, 'Medical Immunology'),
(787, 'Medical Microbiology'),
(788, 'Medical Molecular Biology'),
(789, 'Medical Neurobiology'),
(790, 'Medical Nutrition'),
(791, 'Medical Pathology'),
(792, 'Medical Pharmacology'),
(793, 'Medical Physiology'),
(794, 'Medical Toxicology'),
(795, 'Musculoskeletal, Neural, and Ocular Physiology'),
(796, 'Neurosciences'),
(797, 'Physiological Processes'),
(798, 'Reproductive and Urinary Physiology'),
(799, 'Other Medical Sciences'),
(800, 'Medical Specialties'),
(801, 'Allergy and Immunology'),
(802, 'Anesthesiology'),
(803, 'Cardiology'),
(804, 'Critical Care'),
(805, 'Dermatology'),
(806, 'Emergency Medicine'),
(807, 'Endocrinology, Diabetes, and Metabolism'),
(808, 'Family Medicine'),
(809, 'Gastroenterology'),
(810, 'Geriatrics'),
(811, 'Hematology'),
(812, 'Hepatology'),
(813, 'Infectious Disease'),
(814, 'Integrative Medicine'),
(815, 'Internal Medicine'),
(816, 'Nephrology'),
(817, 'Neurology'),
(818, 'Obstetrics and Gynecology'),
(819, 'Oncology'),
(820, 'Ophthalmology'),
(821, 'Orthopedics'),
(822, 'Osteopathic Medicine and Osteopathy'),
(823, 'Otolaryngology'),
(824, 'Palliative Care'),
(825, 'Pathology'),
(826, 'Pediatrics'),
(827, 'Plastic Surgery'),
(828, 'Podiatry'),
(829, 'Preventive Medicine'),
(830, 'Primary Care'),
(831, 'Psychiatry'),
(832, 'Pulmonology'),
(833, 'Radiology'),
(834, 'Rheumatology'),
(835, 'Sleep Medicine'),
(836, 'Sports Medicine'),
(837, 'Surgery'),
(838, 'Trauma'),
(839, 'Tropical Medicine'),
(840, 'Urology'),
(841, 'Other Medical Specialties'),
(842, 'Mental and Social Health'),
(843, 'Animal-Assisted Therapy'),
(844, 'Art Therapy'),
(845, 'Clinical and Medical Social Work'),
(846, 'Cognitive Behavioral Therapy'),
(847, 'Community Health'),
(848, 'Marriage and Family Therapy and Counseling'),
(849, 'Psychiatric and Mental Health'),
(850, 'Psychoanalysis and Psychotherapy'),
(851, 'Substance Abuse and Addiction'),
(852, 'Other Mental and Social Health'),
(853, 'Nanotechnology'),
(854, 'Nanomedicine'),
(855, 'Nursing'),
(856, 'Critical Care Nursing'),
(857, 'Family Practice Nursing'),
(858, 'Geriatric Nursing'),
(859, 'Maternal, Child Health and Neonatal Nursing'),
(860, 'Nursing Administration'),
(861, 'Nursing Midwifery'),
(862, 'Occupational and Environmental Health Nursing'),
(863, 'Pediatric Nursing'),
(864, 'Perioperative, Operating Room and Surgical Nursing'),
(865, 'Psychiatric and Mental Health Nursing'),
(866, 'Public Health and Community Nursing'),
(867, 'Other Nursing'),
(868, 'Optometry'),
(869, 'Organisms'),
(870, 'Algae'),
(871, 'Animals'),
(872, 'Archaea'),
(873, 'Bacteria'),
(874, 'Fungi'),
(875, 'Mesomycetozoea'),
(876, 'Plants'),
(877, 'Viruses'),
(878, 'Pharmacy and Pharmaceutical Sciences'),
(879, 'Medicinal and Pharmaceutical Chemistry'),
(880, 'Natural Products Chemistry and Pharmacognosy'),
(881, 'Pharmaceutics and Drug Design'),
(882, 'Pharmacoeconomics and Pharmaceutical Economics'),
(883, 'Pharmacy Administration, Policy and Regulation'),
(884, 'Other Pharmacy and Pharmaceutical Sciences'),
(885, 'Psychiatry and Psychology'),
(886, 'Behavior and Behavior Mechanisms'),
(887, 'Behavioral Disciplines and Activities'),
(888, 'Dance Movement Therapy'),
(889, 'Mental Disorders'),
(890, 'Psychological Phenomena and Processes'),
(891, 'Other Psychiatry and Psychology'),
(892, 'Public Health'),
(893, 'Clinical Epidemiology'),
(894, 'Community Health and Preventive Medicine'),
(895, 'Environmental Public Health'),
(896, 'Epidemiology'),
(897, 'Health and Medical Physics'),
(898, 'Health Services Administration'),
(899, 'Health Services Research'),
(900, 'Influenza Humans'),
(901, 'Influenza Virus Vaccines'),
(902, 'International Public Health'),
(903, 'Maternal and Child Health'),
(904, 'Occupational Health and Industrial Hygiene'),
(905, 'Public Health Education and Promotion'),
(906, 'Women\'s Health'),
(907, 'Other Public Health'),
(908, 'Rehabilitation and Therapy'),
(909, 'Kinesiotherapy'),
(910, 'Movement and Mind-Body Therapies'),
(911, 'Occupational Therapy'),
(912, 'Orthotics and Prosthetics'),
(913, 'Physical Therapy'),
(914, 'Physiotherapy'),
(915, 'Recreational Therapy'),
(916, 'Respiratory Therapy'),
(917, 'Somatic Bodywork and Related Therapeutic Practices'),
(918, 'Vocational Rehabilitation Counseling'),
(919, 'Other Rehabilitation and Therapy'),
(920, 'Sports Sciences'),
(921, 'Translational Medical Research'),
(922, 'Veterinary Medicine'),
(923, 'Comparative and Laboratory Animal Medicine'),
(924, 'Large or Food Animal and Equine Medicine'),
(925, 'Small or Companion Animal Medicine'),
(926, 'Veterinary Anatomy'),
(927, 'Veterinary Infectious Diseases'),
(928, 'Veterinary Microbiology and Immunobiology'),
(929, 'Veterinary Pathology and Pathobiology'),
(930, 'Veterinary Physiology'),
(931, 'Veterinary Preventive Medicine, Epidemiology, and Public Health'),
(932, 'Veterinary Toxicology and Pharmacology'),
(933, 'Other Veterinary Medicine'),
(934, 'Other Medicine and Health Sciences'),
(935, 'Physical Sciences and Mathematics'),
(936, 'Applied Mathematics'),
(937, 'Control Theory'),
(938, 'Dynamic Systems'),
(939, 'Non-linear Dynamics'),
(940, 'Numerical Analysis and Computation'),
(941, 'Ordinary Differential Equations and Applied Dynamics'),
(942, 'Partial Differential Equations'),
(943, 'Special Functions'),
(944, 'Other Applied Mathematics'),
(945, 'Astrophysics and Astronomy'),
(946, 'Cosmology, Relativity, and Gravity'),
(947, 'External Galaxies'),
(948, 'Instrumentation'),
(949, 'Physical Processes'),
(950, 'Stars, Interstellar Medium and the Galaxy'),
(951, 'The Sun and the Solar System'),
(952, 'Other Astrophysics and Astronomy'),
(953, 'Chemistry'),
(954, 'Analytical Chemistry'),
(955, 'Environmental Chemistry'),
(956, 'Inorganic Chemistry'),
(957, 'Materials Chemistry'),
(958, 'Medicinal-Pharmaceutical Chemistry'),
(959, 'Organic Chemistry'),
(960, 'Physical Chemistry'),
(961, 'Polymer Chemistry'),
(962, 'Radiochemistry'),
(963, 'Other Chemistry'),
(964, 'Computer Sciences'),
(965, 'Artificial Intelligence and Robotics'),
(966, 'Information Security'),
(967, 'Databases and Information Systems'),
(968, 'Graphics and Human Computer Interfaces'),
(969, 'Numerical Analysis and Scientific Computing'),
(970, 'OS and Networks'),
(971, 'Programming Languages and Compilers'),
(972, 'Software Engineering'),
(973, 'Systems Architecture'),
(974, 'Theory and Algorithms'),
(975, 'Other Computer Sciences'),
(976, 'Earth Sciences'),
(977, 'Biogeochemistry'),
(978, 'Cosmochemistry'),
(979, 'Geochemistry'),
(980, 'Geology'),
(981, 'Geomorphology'),
(982, 'Geophysics and Seismology'),
(983, 'Glaciology'),
(984, 'Hydrology'),
(985, 'Mineral Physics'),
(986, 'Paleobiology'),
(987, 'Paleontology'),
(988, 'Sedimentology'),
(989, 'Soil Science'),
(990, 'Speleology'),
(991, 'Stratigraphy'),
(992, 'Tectonics and Structure'),
(993, 'Volcanology'),
(994, 'Other Earth Sciences'),
(995, 'Environmental Sciences'),
(996, 'Environmental Education'),
(997, 'Environmental Health and Protection'),
(998, 'Environmental Indicators and Impact Assessment'),
(999, 'Environmental Monitoring'),
(1000, 'Natural Resource Economics'),
(1001, 'Natural Resources and Conservation'),
(1002, 'Natural Resources Management and Policy'),
(1003, 'Oil, Gas, and Energy'),
(1004, 'Sustainability'),
(1005, 'Water Resource Management'),
(1006, 'Other Environmental Sciences'),
(1007, 'Mathematics'),
(1008, 'Algebra'),
(1009, 'Algebraic Geometry'),
(1010, 'Analysis'),
(1011, 'Discrete Mathematics and Combinatorics'),
(1012, 'Dynamical Systems'),
(1013, 'Geometry and Topology'),
(1014, 'Harmonic Analysis and Representation'),
(1015, 'Logic and Foundations'),
(1016, 'Number Theory'),
(1017, 'Set Theory'),
(1018, 'Other Mathematics'),
(1019, 'Oceanography and Atmospheric Sciences and Meteorology'),
(1020, 'Atmospheric Sciences'),
(1021, 'Climate'),
(1022, 'Fresh Water Studies'),
(1023, 'Meteorology'),
(1024, 'Oceanography'),
(1025, 'Other Oceanography and Atmospheric Sciences and Meteorology'),
(1026, 'Physics'),
(1027, 'Atomic, Molecular and Optical Physics'),
(1028, 'Biological and Chemical Physics'),
(1029, 'Condensed Matter Physics'),
(1030, 'Elementary Particles and Fields and String Theory'),
(1031, 'Engineering Physics'),
(1032, 'Fluid Dynamics'),
(1033, 'Nuclear'),
(1034, 'Optics'),
(1035, 'Plasma and Beam Physics'),
(1036, 'Quantum Physics'),
(1037, 'Statistical, Nonlinear, and Soft Matter Physics'),
(1038, 'Other Physics'),
(1039, 'Statistics and Probability'),
(1040, 'Applied Statistics'),
(1041, 'Biometry'),
(1042, 'Biostatistics'),
(1043, 'Categorical Data Analysis'),
(1044, 'Clinical Trials'),
(1045, 'Design of Experiments and Sample Surveys'),
(1046, 'Institutional and Historical'),
(1047, 'Longitudinal Data Analysis and Time Series'),
(1048, 'Microarrays'),
(1049, 'Multivariate Analysis'),
(1050, 'Probability'),
(1051, 'Statistical Methodology'),
(1052, 'Statistical Models'),
(1053, 'Statistical Theory'),
(1054, 'Survival Analysis'),
(1055, 'Vital and Health Statistics'),
(1056, 'Other Statistics and Probability'),
(1057, 'Other Physical Sciences and Mathematics'),
(1058, 'Social and Behavioral Sciences'),
(1059, 'Agricultural and Resource Economics'),
(1060, 'Food Security'),
(1061, 'Animal Studies'),
(1062, 'Anthropology'),
(1063, 'Archaeological Anthropology'),
(1064, 'Biological and Physical Anthropology'),
(1065, 'Folklore'),
(1066, 'Linguistic Anthropology'),
(1067, 'Social and Cultural Anthropology'),
(1068, 'Other Anthropology'),
(1069, 'Communication'),
(1070, 'Broadcast and Video Studies'),
(1071, 'Communication Technology and New Media'),
(1072, 'Critical and Cultural Studies'),
(1073, 'Gender, Race, Sexuality, and Ethnicity in Communication'),
(1074, 'Graphic Communications'),
(1075, 'Health Communication'),
(1076, 'International and Intercultural Communication'),
(1077, 'Interpersonal and Small Group Communication'),
(1078, 'Journalism Studies'),
(1079, 'Mass Communication'),
(1080, 'Organizational Communication'),
(1081, 'Public Relations and Advertising'),
(1082, 'Publishing'),
(1083, 'Social Influence and Political Communication'),
(1084, 'Social Media'),
(1085, 'Speech and Rhetorical Studies'),
(1086, 'Other Communication'),
(1087, 'Counseling'),
(1088, 'Counselor Education'),
(1089, 'Economics'),
(1090, 'Behavioral Economics'),
(1091, 'Econometrics'),
(1092, 'Economic History'),
(1093, 'Economic Theory'),
(1094, 'Finance'),
(1095, 'Growth and Development'),
(1096, 'Health Economics'),
(1097, 'Income Distribution'),
(1098, 'Industrial Organization'),
(1099, 'International Economics'),
(1100, 'Labor Economics'),
(1101, 'Macroeconomics'),
(1102, 'Political Economy'),
(1103, 'Public Economics'),
(1104, 'Regional Economics'),
(1105, 'Other Economics'),
(1106, 'Environmental Studies'),
(1107, 'Food Studies'),
(1108, 'Geography'),
(1109, 'Geographic Information Sciences'),
(1110, 'Human Geography'),
(1111, 'Nature and Society Relations'),
(1112, 'Physical and Environmental Geography'),
(1113, 'Remote Sensing'),
(1114, 'Spatial Science'),
(1115, 'Other Geography'),
(1116, 'International and Area Studies'),
(1117, 'African Studies'),
(1118, 'Asian Studies'),
(1119, 'Eastern European Studies'),
(1120, 'Latin American Studies'),
(1121, 'Near and Middle Eastern Studies'),
(1122, 'Soviet and Post-Soviet Studies'),
(1123, 'Other International and Area Studies'),
(1124, 'Leadership Studies'),
(1125, 'Legal Studies'),
(1126, 'Criminology and Criminal Justice'),
(1127, 'Forensic Science and Technology'),
(1128, 'Legal Theory'),
(1129, 'Other Legal Studies'),
(1130, 'Leisure Studies'),
(1131, 'Library and Information Science'),
(1132, 'Archival Science'),
(1133, 'Cataloging and Metadata'),
(1134, 'Collection Development and Management'),
(1135, 'Information Literacy'),
(1136, 'Scholarly Communication'),
(1137, 'Scholarly Publishing'),
(1138, 'Linguistics'),
(1139, 'Anthropological Linguistics and Sociolinguistics'),
(1140, 'Applied Linguistics'),
(1141, 'Comparative and Historical Linguistics'),
(1142, 'Computational Linguistics'),
(1143, 'Discourse and Text Linguistics'),
(1144, 'First and Second Language Acquisition'),
(1145, 'Language Description and Documentation'),
(1146, 'Morphology'),
(1147, 'Phonetics and Phonology'),
(1148, 'Psycholinguistics and Neurolinguistics'),
(1149, 'Semantics and Pragmatics'),
(1150, 'Syntax'),
(1151, 'Typological Linguistics and Linguistic Diversity'),
(1152, 'Other Linguistics'),
(1153, 'Organization Development'),
(1154, 'Political Science'),
(1155, 'American Politics'),
(1156, 'Comparative Politics'),
(1157, 'International Relations'),
(1158, 'Models and Methods'),
(1159, 'Political Theory'),
(1160, 'Other Political Science'),
(1161, 'Psychology'),
(1162, 'Applied Behavior Analysis'),
(1163, 'Biological Psychology'),
(1164, 'Child Psychology'),
(1165, 'Clinical Psychology'),
(1166, 'Cognition and Perception'),
(1167, 'Cognitive Psychology'),
(1168, 'Community Psychology'),
(1169, 'Comparative Psychology'),
(1170, 'Counseling Psychology'),
(1171, 'Developmental Psychology'),
(1172, 'Experimental Analysis of Behavior'),
(1173, 'Health Psychology'),
(1174, 'Industrial and Organizational Psychology'),
(1175, 'Multicultural Psychology'),
(1176, 'Pain Management'),
(1177, 'Personality and Social Contexts'),
(1178, 'Quantitative Psychology'),
(1179, 'School Psychology'),
(1180, 'Social Psychology'),
(1181, 'Theory and Philosophy'),
(1182, 'Transpersonal Psychology'),
(1183, 'Other Psychology'),
(1184, 'Public Affairs, Public Policy and Public Administration'),
(1185, 'Defense and Security Studies'),
(1186, 'Economic Policy'),
(1187, 'Education Policy'),
(1188, 'Emergency and Disaster Management'),
(1189, 'Energy Policy'),
(1190, 'Environmental Policy'),
(1191, 'Health Policy'),
(1192, 'Infrastructure'),
(1193, 'Military and Veterans Studies'),
(1194, 'Peace and Conflict Studies'),
(1195, 'Policy Design, Analysis, and Evaluation'),
(1196, 'Policy History, Theory, and Methods'),
(1197, 'Public Administration'),
(1198, 'Public Affairs'),
(1199, 'Public Policy'),
(1200, 'Recreation, Parks and Tourism Administration'),
(1201, 'Science and Technology Policy'),
(1202, 'Social Policy'),
(1203, 'Social Welfare'),
(1204, 'Terrorism Studies'),
(1205, 'Transportation'),
(1206, 'Urban Studies'),
(1207, 'Other Public Affairs, Public Policy and Public Administration'),
(1208, 'Science and Technology Studies'),
(1209, 'Social Statistics'),
(1210, 'Social Work'),
(1211, 'Sociology'),
(1212, 'Civic and Community Engagement'),
(1213, 'Community-Based Learning'),
(1214, 'Community-Based Research'),
(1215, 'Criminology'),
(1216, 'Demography, Population, and Ecology'),
(1217, 'Domestic and Intimate Partner Violence'),
(1218, 'Educational Sociology'),
(1219, 'Family, Life Course, and Society'),
(1220, 'Gender and Sexuality'),
(1221, 'Gerontology'),
(1222, 'Human Ecology'),
(1223, 'Inequality and Stratification'),
(1224, 'Medicine and Health'),
(1225, 'Place and Environment'),
(1226, 'Politics and Social Change'),
(1227, 'Quantitative, Qualitative, Comparative, and Historical Methodologies'),
(1228, 'Race and Ethnicity'),
(1229, 'Regional Sociology'),
(1230, 'Rural Sociology'),
(1231, 'Service Learning'),
(1232, 'Social Control, Law, Crime, and Deviance'),
(1233, 'Social Psychology and Interaction'),
(1234, 'Sociology of Culture'),
(1235, 'Sociology of Religion'),
(1236, 'Theory, Knowledge and Science'),
(1237, 'Tourism'),
(1238, 'Work, Economy and Organizations'),
(1239, 'Other Sociology'),
(1240, 'Sports Studies'),
(1241, 'Urban Studies and Planning'),
(1242, 'Other Social and Behavioral Sciences');
